#!/bin/bash

GITURL='https://github.com/secretescapes/grails-petclinic'
SOURCE=`basename $GITURL`
CRONPATH="/etc/cron.d/petci"
JAVA_HOME=/usr/lib/jvm/java-8-oracle


# set up crontab once

if [[ ! -e "$CRONPATH" ]]; then
    sudo su -c "echo 'MAILTO=\"\"' > $CRONPATH; echo '*/2 * * * * ' $USER cd $PWD \&\& bash ./installer >> $CRONPATH"
fi

# initial clone of source 
if [[ ! -e $SOURCE ]]; then
git clone $GITURL
# check for clone errors
if [[ "$?" != 0 || ! -e $SOURCE ]] ; then
  echo "cloning of source from github failed"
  exit 1
fi
else
RES=`git pull`
# if nothing has changed on the remote, then take no further action
if [[ "$RES" == "Already up-to-date." ]]; then
    echo "no changes in the repository so nothing to do"
    exit 0
fi
fi

cd $SOURCE 
echo "starting build"
./grailsw war

# provision server, see Vagrantfile
vagrant up --provision



